//! Tool system modules and re-exports.

pub mod a2a;
pub mod agent_graph;
pub mod agent_memory;
pub mod apply_patch;
pub mod approval_cache;
pub mod automation;
pub mod browser;
pub mod diagnostics;
pub mod diff_format;
pub mod file;
pub mod file_search;
pub mod fim_edit;
pub mod finance;
pub mod goap;
pub mod manager_agent;

pub mod fetch_url;
pub mod git;
pub mod git_history;
pub mod github;
pub mod parallel;
pub mod plan;
pub mod profiles;
pub mod project;
pub mod recall_archive;
pub mod registry;
pub mod remember;
pub mod revert_turn;
pub mod review;
pub mod rlm;
pub mod search;
pub mod shell;
mod shell_output;
pub mod skill;
pub mod spec;
pub mod subagent;
pub mod swarm;
pub mod tasks;
pub mod test_runner;
pub mod todo;
pub mod truncate;
pub mod user_input;
pub mod validate_data;
pub mod web_pipeline;
pub mod web_run;
pub mod web_search;

pub use registry::{ToolRegistry, ToolRegistryBuilder};
pub use review::ReviewOutput;
pub use spec::ToolContext;
pub use user_input::UserInputResponse;
