//! Session state management for the core engine.
//!
//! Tracks conversation history, token usage, session metadata, and invoked
//! skill records for compaction durability.

use crate::cycle_manager::CycleBriefing;
use crate::models::{Message, SystemPrompt, Usage};
use crate::project_context::{ProjectContext, load_project_context_with_parents};
use crate::tui::approval::ApprovalMode;
use crate::working_set::WorkingSet;
use chrono::{DateTime, Utc};
use std::collections::HashMap;
use std::path::PathBuf;

/// Record of a skill invoked during the current cycle.
///
/// Persisted so that compaction can re-inject skill content into the
/// post-compact message stream instead of losing it inside summarized
/// tool results.  Repeated invocations of the same skill overwrite the
/// entry (keyed by `skill_name`) so only the latest body + timestamp
/// survive — the Map is the dedup mechanism.
#[derive(Debug, Clone)]
pub struct InvokedSkillRecord {
    pub skill_name: String,
    pub content: String,
    pub invoked_at: DateTime<Utc>,
}

/// Session state for the engine.
#[derive(Debug, Clone)]
pub struct Session {
    /// Model being used
    pub model: String,

    /// Reasoning-effort tier for DeepSeek thinking mode:
    /// `"off" | "low" | "medium" | "high" | "max"`. `None` lets the provider
    /// apply its own defaults.
    pub reasoning_effort: Option<String>,
    /// Whether the user selected automatic reasoning effort.
    pub reasoning_effort_auto: bool,

    /// Whether the user selected automatic model routing.
    pub auto_model: bool,

    /// Workspace directory
    pub workspace: PathBuf,

    /// System prompt (optional)
    pub system_prompt: Option<SystemPrompt>,
    /// Hash of the last assembled stable system prompt. Used to avoid
    /// replacing `system_prompt` when unchanged.
    pub last_system_prompt_hash: Option<u64>,
    /// Persisted summary blocks generated by context compaction.
    pub compaction_summary_prompt: Option<SystemPrompt>,

    /// Conversation history (API format)
    pub messages: Vec<Message>,

    /// Total tokens used in this session
    pub total_usage: SessionUsage,

    /// Whether shell execution is allowed
    pub allow_shell: bool,

    /// Whether to trust paths outside workspace
    pub trust_mode: bool,

    /// Whether the current session should auto-approve tool safety checks.
    pub auto_approve: bool,

    /// Live UI approval policy used to steer the system prompt.
    pub approval_mode: ApprovalMode,

    /// Notes file path
    pub notes_path: PathBuf,

    /// MCP config path
    pub mcp_config_path: PathBuf,

    /// Session ID (for tracking)
    pub id: String,

    /// Project context loaded from AGENTS.md, etc.
    pub project_context: Option<ProjectContext>,

    /// Repo-aware working set for context management.
    pub working_set: WorkingSet,

    /// Number of cycle boundaries crossed in this session (issue #124). The
    /// active cycle index is `cycle_count + 1` (cycles are 1-based for users).
    pub cycle_count: u32,

    /// UTC start time of the *current* cycle. Updated when the engine resets
    /// the conversation buffer. Used by archive headers and the `/cycles`
    /// command's display.
    pub current_cycle_started: DateTime<Utc>,

    /// Briefings produced at past cycle boundaries, in chronological order.
    /// Bounded growth: one entry per cycle, briefing capped at ~3,000 tokens.
    pub cycle_briefings: Vec<CycleBriefing>,

    /// Skills invoked in the current cycle (keyed by skill name so repeat
    /// calls overwrite — the Map itself is the dedup mechanism). Compacted
    /// into synthetic messages so skill content survives summarization.
    pub invoked_skills: HashMap<String, InvokedSkillRecord>,
}

/// Cumulative usage statistics for a session.
#[derive(Debug, Clone, Default)]
#[allow(clippy::struct_field_names)]
pub struct SessionUsage {
    pub input_tokens: u64,
    pub output_tokens: u64,
    #[allow(dead_code)]
    pub cache_creation_input_tokens: u64,
    #[allow(dead_code)]
    pub cache_read_input_tokens: u64,
}

impl SessionUsage {
    /// Add usage from a turn
    pub fn add(&mut self, usage: &Usage) {
        self.input_tokens += u64::from(usage.input_tokens);
        self.output_tokens += u64::from(usage.output_tokens);
        if let Some(tokens) = usage.prompt_cache_miss_tokens {
            self.cache_creation_input_tokens += u64::from(tokens);
        }
        if let Some(tokens) = usage.prompt_cache_hit_tokens {
            self.cache_read_input_tokens += u64::from(tokens);
        }
    }
}

impl Session {
    /// Create a new session
    pub fn new(
        model: String,
        workspace: PathBuf,
        allow_shell: bool,
        trust_mode: bool,
        notes_path: PathBuf,
        mcp_config_path: PathBuf,
    ) -> Self {
        // Load project context from AGENTS.md, CLAUDE.md, etc.
        let project_context = load_project_context_with_parents(&workspace);
        let has_context = project_context.has_instructions();

        Self {
            model,
            reasoning_effort: None,
            reasoning_effort_auto: false,
            auto_model: false,
            workspace,
            system_prompt: None,
            compaction_summary_prompt: None,
            messages: Vec::new(),
            total_usage: SessionUsage::default(),
            allow_shell,
            trust_mode,
            auto_approve: false,
            approval_mode: ApprovalMode::Suggest,
            notes_path,
            mcp_config_path,
            id: uuid::Uuid::new_v4().to_string(),
            project_context: if has_context {
                Some(project_context)
            } else {
                None
            },
            last_system_prompt_hash: None,
            working_set: WorkingSet::default(),
            invoked_skills: HashMap::new(),
            cycle_count: 0,
            current_cycle_started: Utc::now(),
            cycle_briefings: Vec::new(),
        }
    }

    /// Add a message to the conversation
    pub fn add_message(&mut self, message: Message) {
        self.messages.push(message);
    }

    /// Rebuild the working set from current messages (best effort).
    pub fn rebuild_working_set(&mut self) {
        self.working_set
            .rebuild_from_messages(&self.messages, &self.workspace);
    }

    /// Record a skill invocation so compaction can re-inject its content.
    /// Repeat calls with the same `skill_name` overwrite the previous
    /// record — the `HashMap` key is the dedup mechanism.
    pub fn record_skill_invocation(&mut self, skill_name: String, content: String) {
        self.invoked_skills.insert(
            skill_name.clone(),
            InvokedSkillRecord {
                skill_name,
                content,
                invoked_at: Utc::now(),
            },
        );
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test_session() -> Session {
        Session::new(
            "deepseek-v4-pro".to_string(),
            std::path::PathBuf::from("."),
            true,
            false,
            std::path::PathBuf::from("notes.txt"),
            std::path::PathBuf::from("mcp.json"),
        )
    }

    #[test]
    fn record_skill_invocation_stores_entry() {
        let mut session = test_session();
        assert!(session.invoked_skills.is_empty());

        session.record_skill_invocation(
            "security-review".to_string(),
            "# Security Review\n\nCheck for vulnerabilities.".to_string(),
        );

        assert_eq!(session.invoked_skills.len(), 1);
        let record = session.invoked_skills.get("security-review").unwrap();
        assert_eq!(record.skill_name, "security-review");
        assert!(record.content.contains("Security Review"));
        assert!(record.content.contains("vulnerabilities"));
    }

    #[test]
    fn repeat_skill_invocation_overwrites_and_deduplicates() {
        let mut session = test_session();

        session.record_skill_invocation(
            "review-pr".to_string(),
            "v1: simple review".to_string(),
        );

        let first_invoked_at = session
            .invoked_skills
            .get("review-pr")
            .unwrap()
            .invoked_at;

        // Small sleep to ensure timestamp differs.
        std::thread::sleep(std::time::Duration::from_millis(5));

        session.record_skill_invocation(
            "review-pr".to_string(),
            "v2: detailed review with checklists".to_string(),
        );

        // Still only one entry — dedup by name.
        assert_eq!(session.invoked_skills.len(), 1);
        let record = session.invoked_skills.get("review-pr").unwrap();
        assert!(record.content.contains("v2"));
        assert!(!record.content.contains("v1"));
        // Timestamp must have advanced.
        assert!(record.invoked_at > first_invoked_at);
    }

    #[test]
    fn multiple_different_skills_accumulate() {
        let mut session = test_session();

        session.record_skill_invocation("a".to_string(), "body a".to_string());
        session.record_skill_invocation("b".to_string(), "body b".to_string());
        session.record_skill_invocation("c".to_string(), "body c".to_string());

        assert_eq!(session.invoked_skills.len(), 3);
        assert!(session.invoked_skills.contains_key("a"));
        assert!(session.invoked_skills.contains_key("b"));
        assert!(session.invoked_skills.contains_key("c"));
    }

    #[test]
    fn invoked_skills_is_initially_empty() {
        let session = test_session();
        assert!(session.invoked_skills.is_empty());
    }
}
